### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by thegargiulian** [mashrur-ayon/genderstat#5]
I'd recommend simplifying the installation instructions to just `install.packages("genderstat")`. 

You're already managing the `ggplot2` and `tidyverse` dependencies automatically in the `DESCRIPTION` file, so there's no need to include those dependencies in the installation instructions. The same goes for the dependency description you have in the README. 

_This issue is with reference to the JOSS review here https://github.com/openjournals/joss-reviews/issues/5932_

**Comment by mashrur-ayon** [comment]
I have resolved the issue, and in the new version I have removed the need for `ggplot2` and `tidyverse`. A major reason for this is because, after taking into consideration of your suggestion I have removed the plotting functions from this version of `genderstat`. Maybe I will create another package with just the plotting function later on.
